### ISSUE TITLE
Echo !$CRLF! print 'on' or 'off' instead of a single new line

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#6] opened 2019-08-23 05:38 UTC
echo !$CRLF! show the status instead of print an empty line.
It should print only a new line.

**Comment by adoxa** [comment] 2019-08-23 06:14
Isn't this really just a duplicate of #5?

**Comment by carlos-montiers** [comment] 2019-08-23 13:51
> Isn't this really just a duplicate of #5?

Mmm, if #5 is solved, then this will be solved. I posted separated because this issue is a bug and #5 is an enhancement.

**Comment by adoxa** [comment] 2019-08-25 08:43
Fixed in c7b8acb. But note that `echo !$CRLF!` will output two blank lines, not one (`echo` will output one blank line).

**Closed by adoxa** 2019-08-25 08:43 UTC
Labels: bug
